name: IAST - ZAP Runtime Scan

on:
  push:
    branches: [ "main" ]

jobs:
  zap:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Test app reachable
        run: |
          curl -I http://47.129.223.141:8080/api/hello

      - name: Run ZAP scan
        run: |
          docker pull ghcr.io/zaproxy/zaproxy:stable
          docker run --rm \
            -v "$PWD:/zap/wrk/:rw" \
            --network=host \
            ghcr.io/zaproxy/zaproxy:stable \
            zap-baseline.py \
              -t http://47.129.223.141:8080/api/hello \
              -J report.json -w report.md -r report.html -a

      - name: Upload report
        uses: actions/upload-artifact@v4
        with:
          name: zap-report
          path: |
            report.html
            report.md
            report.json
